version: '2.0'
services:
  nginx:
    image: slyak/nginx
    restart: always
    ports:
      - 80:80
#    depends_on:
#      - jira
#      - crowd
    env_file:
      - common.env
    networks:
      dev:
        aliases:
          - dev.slyak.com

#  jira:
#    image: slyak/jira
#    restart: always
#    volumes:
#      - /var/atlassian/jira:/var/atlassian/jira
#    env_file:
#      - common.env
#    networks:
#      dev:
#        aliases:
#          - jira

#  bamboo:
#    image: slyak/bamboo
#    restart: always
#    volumes:
#      - /var/atlassian/bamboo:/var/atlassian/bamboo
#      - /var/atlassian/bamboo/logs:/opt/atlassian/bamboo/logs
#    env_file:
#      - common.env
#    networks:
#      dev:
#        aliases:
#          - bamboo

#  bitbucket:
#    image: slyak/bitbucket
#    restart: always
#    links:
#      - crowd
#    volumes:
#      - /var/atlassian/bitbucket:/var/atlassian/bitbucket
#      - /var/atlassian/bitbucket/logs:/opt/atlassian/bitbucket/logs
#    env_file:
#      - common.env
#    networks:
#      dev:
#        aliases:
#          - bitbucket

  confluence:
    image: slyak/confluence
    restart: always
    links:
      - crowd
    volumes:
      - /var/atlassian/confluence:/var/atlassian/confluence
      - /var/atlassian/confluence/logs:/opt/atlassian/confluence/logs
    env_file:
      - common.env
    networks:
      dev:
        aliases:
          - confluence

#  fecru:
#    image: slyak/fecru
#    restart: always
#    links:
#      - crowd
#    volumes:
#      - /var/atlassian/fisheye:/var/atlassian/fisheye
#    env_file:
#      - common.env
#    networks:
#      dev:
#        aliases:
#          - fecru

  crowd:
      image: slyak/crowd
      restart: always
      volumes:
        - /var/atlassian/crowd:/var/atlassian/crowd
      env_file:
        - common.env
      networks:
        dev:
          aliases:
            - crowd

#  mysql:
#    image: mysql:5
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - /var/slyak/mysql:/etc/mysql/conf.d
#      - /opt/slyak/mysql:/var/lib/mysql

#  portainer:
#    image: portainer/portainer
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    networks:
#      dev:
#        aliases:
#          - portainer

networks:
  dev: