version: '2.0'
services:
  nginx:
    image: hub.slyak.com/nginx
    restart: always
    ports:
      - 80:80
    links:
      - jira
      - bamboo
      - bitbucket
      - confluence
      - fecru
      - crowd
    volumes:
      - /etc/nginx:/etc/nginx
      - /usr/share/nginx:/usr/share/nginx
    env_file:
      - common.env

  jira:
    image: hub.slyak.com/jira
    restart: always
#    ports:
#      - 8080:8080
    environment:
      - CROWD_BASE_URL=${SERVER_NAME}/crowd
    volumes:
      - /var/atlassian/jira:/var/atlassian/jira
    env_file:
      - common.env


#  bamboo:
#    image: hub.slyak.com/bamboo
#    restart: always
##    ports:
##      - 8085:8085
##      - 54663:54663
#    links:
#      - crowd
#    volumes:
#      - /var/atlassian/bamboo:/var/atlassian/bamboo
#      - /var/atlassian/bamboo/logs:/opt/atlassian/bamboo/logs
#    env_file:
#      - common.env

#  bitbucket:
#    image: hub.slyak.com/bitbucket
#    restart: always
##    ports:
##      - 7990:7990
##      - 7999:7999
#    links:
#      - crowd
#    volumes:
#      - /var/atlassian/bitbucket:/var/atlassian/bitbucket
#      - /var/atlassian/bitbucket/logs:/opt/atlassian/bitbucket/logs
#    env_file:
#      - common.env

#  confluence:
#    image: hub.slyak.com/confluence
#    restart: always
##    ports:
##      - 8090:8090
#    links:
#      - crowd
#    volumes:
#      - /var/atlassian/confluence:/var/atlassian/confluence
#      - /var/atlassian/confluence/logs:/opt/atlassian/confluence/logs
#    env_file:
#      - common.env

#  fecru:
#    image: hub.slyak.com/fecru
#    restart: always
##    ports:
##      - 8060:8060
#    links:
#      - crowd
#    volumes:
#      - /var/atlassian/fisheye:/var/atlassian/fisheye
#    env_file:
#      - common.env

  crowd:
      image: hub.slyak.com/crowd
      restart: always
#      ports:
#        - 8095:8095
      volumes:
        - /var/atlassian/crowd:/var/atlassian/crowd
      env_file:
        - common.env

#  mysql:
#    image: mysql:5
#    restart: always
#    ports:
#      - 3306:3306
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#    volumes:
#      - /var/slyak/mysql:/etc/mysql/conf.d
#      - /opt/slyak/mysql:/var/lib/mysql
#
#  portainer:
#    image: portainer/portainer
#    restart: always
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - 9000:9000