version: '2.0'
services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - /opt/nginx/html:/usr/share/nginx/html
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx/conf.d:/etc/nginx/conf.d

  bamboo:
    image: docker.slyak.com/bamboo
    ports:
      - 8081:8080
    links:
    volumes:
      - /opt/atlassian/bamboo:/

  clover:
  confluence:
    image: docker.slyak.com/bamboo
    ports:
      - 8080:8080
    links:
    volumes:
      - /opt/atlassian/bamboo:/
  crowd:
  crucible:
  fisheye:
  jira:
  stash: